name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ./CleanArchitecture.sln

      - name: Build
        run: dotnet build ./CleanArchitecture.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./CleanArchitecture.sln --configuration Release --no-restore --no-build
